apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:yIuWLrc=,iv:GWrmXpxTBaEwf2Tpijp7qLrocFPUgbG81ev9GJ6Ntrg=,tag:qfu2bHejIlAepxCkZGz5ZA==,type:str]
    admin-password: ENC[AES256_GCM,data:k4dbvtRlNBkg6g1ldcBT7A==,iv:Ses3otZC3phAzZdBowEYiKnIXDRUWw601AGb4+tPifw=,tag:EgwxyYmtNW7lEPU23Vob1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbEhzYjFRem5LOENDeWZj
            bEtmRlVESlhLQ2FvcFJtd1orZDBSNzloa0dFCk04MDgyRCtsRld6amdPajF6VmpT
            RDN2ZzBqSlpOblFlcno5eWx6bk9XdGMKLS0tIERvdGlhQTcwT1FZZGJuU0ZvZk1E
            WHdwWkpiRVBVMDNSVGV5OVJDbVFHaWcKIqvPnuvbeZt/iWSWQmbe+WJBvOXEzTuR
            TDNWJ8AZp1XdrYPyoD84uIJxduHpUMHSt+/r+ySSOUnq/tLtVpC/lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T22:06:12Z"
    mac: ENC[AES256_GCM,data:IFtrQxbx1HLLQho7eqlOLOM8jNbRC3vB9wzEoR3jLSqrhyIh9t9NBysP25ULOCfUu9xKtM4AwQ7EzF5Iz5W0VQi2ov+iq80lhr4h+GiOfV4zmqZHj44X9TjaWdy1QQlBx9bdBibc7JKnQNGKA2h8BLyztghRj8dQrKja/J2Vm8k=,iv:xc5G2v9amIumuahf8AmkCfgYeKbi2X/7Osdpk3gi2rs=,tag:MvOFdfs1SSHnFyYB6jOAYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
