apiVersion: v1
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1rpNNVzmffnR6kUNKdfFdZZzYYY=,iv:VKesw/q6afNES4CgcKdxrwIp5qSuM3WDiF45chbSns4=,tag:QXIZletuFrBrU9HmiLD89g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uEMftA6T87kFnmdRZDccg/cxVXl20QN+z0BbZZv2CKdnyZlOhSd72Q==,iv:3IxWdanUhWLZDVUJXUhxXFkajmoH8kTSKlVmc7eq04w=,tag:YIbaAHnVCjUdKmgxdeAHPg==,type:str]
    values.yaml: ENC[AES256_GCM,data:Q3JFY2Pe8fVYzDn4ypb5dvaaoL5u15cG+g+D/aWY0wImwgzgh9YclD6NG+1vf786W23e5DZpASno78lsoMFP6pfjwv9ZP/0vSP/Wx13ApS3If0s4YnbctkUxdkZepJggENE3zSTDfgQgtGrLD6AfduM5Cue0ZCTMr0rg16GzwGkBbjb4fGUqdIQLnqFTfUJjTsCur/82gGmC/ewNh43xsBb5YfcUrWFNBWdcp2K7pk3vPwlpuKerXaRgqoUUnzYwAhSXEdgg7vggLK+bwiCbVl2jzO0Blzry6XAiLFS4AChk7gAPI0N59mRBlgU+kOPTcEAhT7fjLQ6cUW5ffB8FKCTG3HH/D7Lva12mgNMwlVRLuJISfs0dp0Wg8IMwB9QxXDUD3+Arp/vyZ3ydmmaHXKy19N7a2eSZJPSUuCRVVw==,iv:RA/PyNSXSRvGYZjBzKn0d/h23+OzechtN9WRFgKe9pQ=,tag:ZA3ICicFuo2dtPjPYB3tYg==,type:str]
kind: Secret
metadata:
    name: s3-eu-north-1-ctrl
    namespace: velero
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVytrSStCOXZZQmh6SjYx
            Q3R1d0dRbyttenJhNWUrRDYwYWxvNTcxcEZFCkxWd1dBSlZxbmRDTStwYzdDakhZ
            VTZ3cGJNUVJvKzZGS0RKazh1Sjk3WVkKLS0tIGlkYUNodk1yVGZ4dlpwM0t3WGw1
            dzVkQnE4aHlaN2haQTN3RkYvbGxpWmsKFbCdXdxo5ct6tfhiV1tHg8MhA9zBNCoh
            OqL85Ya1GKCb3tQIchLpsqlPnAHHfG3vh9E5RDBUNqurHFxKl1bJOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T23:13:59Z"
    mac: ENC[AES256_GCM,data:IrbC55J8d4DFgDQzSTx6Yv5YyBIPXpj3Na6kxWRNb0zrP0pU2e71mj8wYaKqvyfTVTHf+qZxMrvMB0TX6eil8G3F8OFs/KTMhuxnbomAlHJiZXUTnPXjcoX4HzfJp+jMaO9GLBSiK/1aqlJesGcnY6FGdiUaIjnEDzIJBdaFQek=,iv:Fi1MNxMLCUzXYtbCCp36DOI+GAcZQi2pDBO6hY9gUao=,tag:UnrrcCEVu8heAUWaB0Rl7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
