apiVersion: v1
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:i2HiTPTSxGUeXlUwVVGBui3gksg=,iv:j2JiRaaog5Tu5ggULPaTcsRO3c4jAyNM23QvrCesKjY=,tag:rKeMx8DrGZDsTE1qfTMxMQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qZgj5pqS7roeEbKf4EVEyWcA84dpztAbBigKT3FH3JNaRa075Fhq3g==,iv:LJr0mW38vd7ALillq7w8DYq4ypcWqezR5YRHNe5N5fs=,tag:u7vG2cqJCpq2YKD4CSS1Mw==,type:str]
    values.yaml: ENC[AES256_GCM,data:SxH1lL8P80FBvfJTPOHvvyjuxrTMrxXLc2VrdjTe5nU2HcWuDF9iFLuvbzJ2FDyN/xo02d46Tz4QjXgpw3V3hwarBAxZxKD6BmXP4rFVYh2kfr99tWVRCIAw3s5ON5c8bZB/aszPdt9vRrQK+wU/eRHCSF0bswIz1pH+X4jn5YD4Y1vnx6BvKOZ0GVFHo4mGIR2G+ECxbdszGIk3+9nvdUrmHIW8dob1m/ZtfceuToAkrc+BdVNqXEDdnyKBikRmhMT1GmAyXUaVwHXZIalkX0vn4v08gEGSPGRPSqE/2S1JuLHO7YycmfPcyQCIp3J+v19eFa/pl9Si0Ug8HN4u5d0JRbYrt7odae+iVtIPO6btA2afSdnKHN7YRlUCsZ8sLg36/7XSL+780L4P1dS0VBqQ5naL63MMZ1QP2R/vew==,iv:ZaDZsbMfEAcoA6ishJ1wxWrqbtgcWt0lyWQqCeT2a44=,tag:oYGzvRzaNuPYre50CbqoVQ==,type:str]
kind: Secret
metadata:
    name: s3-eu-north-1-ctrl
    namespace: velero
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZjhDaUo4Y3NKNnRkdU5p
            UEZSU3dxK1VlR080MnJ4UTRZdXlDVHdBa1VJCjF6THJKYXF1VUFubGFoeHlZU3Y1
            TzZ4NHovUExrOGtyS09DWnY4aDkvUEEKLS0tIHRGd3IyaVFOZWNNVDVCbzd0Q3ZB
            ZGVkbndVMkpmNCt5SnFOa1pEMTBQTTQKI1BSQKKyRBHVydrOUknwUPshMTQsr7mV
            ptaQ3sk+1iGuYz6C4f7sa1BXeaDObonVtIEK6y+aku3hKY6OBKpZtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T03:45:03Z"
    mac: ENC[AES256_GCM,data:2rHl/cQ6WdhzHaZZpI/t2wYkuRUlCLGyTNKz5zRBtvQakT5Mvlz8OsDzqQzS/sj3R3AqsiqY+SHUNrk5gtX06b3LBsUcUv4NoqK0vlLVvotNYrxdUE+PNLQd+gTOk0j1QXD9cBhanM6XRV3YKyIjzXWuUxQ2G0m9TDwjRLe4u0g=,iv:HCMkylDt0N6Et6R3qQ/YLtGirst/aitutgQ2t57oj74=,tag:8+yumYNrARidWt4uWNyvtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
