apiVersion: v1
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SJ2nhDJRziOukgMPsw0epCssVmA=,iv:VbAQtitQk6spj6Q3gKyNNozFzRaC/e1FPQenglyVFhs=,tag:pzK4ZaSRAB/gpAUqogf3xw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3Zilom6NvsshFYM37wwD+1qLgiJmjRedO8Eb23T+M1ulHLpuo73FAw==,iv:3BpDI26c/2/2rCT6MnugbQcXv7Drr0DC+sYSneJVGlE=,tag:0er0XiXPb9BYxZJNFKGhTA==,type:str]
    values.yaml: ENC[AES256_GCM,data:VEkyCDkPAZ2LkNKiE4wuazfPW8+zn4ngdY6fMfNfMJnwfGIdcNWJ0eLuomppKDTMHSscGhDkjrwhkSHGFYF8Wg93CsZQNYR0PQq2RdzERqQAIfRf4TaLf4bWGCQamoULkLQfou3yMdC8rCInB8Wteq61Ed7OEdB7SFcIGpJyQhiuDLkvLFonA6YgXSycNw9xm0KEWsIn7lRoDY9oRaJuC5sgeid83jdDBp7n93oohhltOlzVUiqVtKDzjeOsiPe1CF/zH1ZF0bh/C2R3K1b91cLm/TrvUBoKuYgeaDRo/oeWWDUNyGPQiNF2f5FdxnDRPnaNbUsgy+HqFnn33izdMI6AAAFgP+XHI2C4cA7Jv1BOiOqeHOOp8VHhVXxtU3gP8zljSq9VGJHoZM6vHRIW1bviUPm3W0V2nvs0KDrytg==,iv:hcauwooTyGkpDLVOqM13in8USYKizJInhtHdF/qH6jY=,tag:oxOsk79XeAJI7KB4W8HhYw==,type:str]
kind: Secret
metadata:
    name: s3-eu-north-1-ctrl
    namespace: velero
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRanpVUUdPNkV1eC9pZkMx
            M1BsY3VKR2FybXBtcEp3UG5YZVFKVkcvc1dFCkFWU1JJUWlEZUVjcmlIcnRkWkFY
            elZodExRVnJETkFwdzNiUm9VcmVVK0EKLS0tIFhUckNUYTdvZkg1Z29WUmxoZE83
            bHhXTUlyVE1WT0VLQW02eG9DMlZLOVEKxhziZa80DjVuvh7EKB7wGnWcwLOIRocg
            nxhAKDjJCDagYTdftP+A+bpZ8L4GfghUpi2MakIYxsM0mujlu3TFGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T16:51:44Z"
    mac: ENC[AES256_GCM,data:RBua/+0L/to5EbLM99VKZlKqqdpR1DosvuQZn20yXmiVitQJht+xIPdMy0uOxQih0uCtvF3ujuDp4MvX+L6HVXDmRpXdeVBQkCE9gkv3xEMrzFW3RNZOFzUVFc1tkcbHJByyCZvbcFjoy+IZUH0PkbqyHcTegsjzbo2LQiL3mk8=,iv:OZSECwFMQvd7nCxH8L85k8Wx326uVDJ9TK0QibT+1bk=,tag:Z/8nb8fWi8hspu/HW7ayeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
