apiVersion: v1
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XJR1sPjv+1bmrnFbDKaC5I/LGcA=,iv:lxMMdPVMmf9TkErmrpuhgE6fFcOFpzQJ6YDmM6QEQdQ=,tag:0Vrn9mLBnS6ZBVWpim4ldQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PpAmQcDSlrH1PDIj0JhSH76CyUAtQCdxgSKE3ttdCWfXyvWMzNzBIw==,iv:EciUCyBDz+gkQbcAVd0lNKwash5mvwMunkgtBDgiCgc=,tag:4/1kjVSwCTEzYuOLtRWg4A==,type:str]
    values.yaml: ENC[AES256_GCM,data:lKINv0DhCmNlX2Pjoqk/fedKOeU/UeOIvuMhUhTKMH3vba1TCAkjuVhdOH1WVD0n0fyaCLxTxu+MBXw8KTz/5BCNMO1cKRX2glU1GXkveUgcxgoIjM+lv7CyjIO6PaCrxp+dGDb+y3GKlZKfnvEdymRLqruc5/N72nb/LXK0lfzWHy4+livhY9zatoWzNrfjAKGHG/DOQ2i1AFDslrjnGVs+9WevFvdvwRYRjOIqsaDqMVIZpew3LNjneBaje88F+mT8SQ+WG+dUJwMJ/xy0I2HUOHi1u0MEDsmMz4WK4z8MBQqvINvh4jRPa/wX5i3L5uHPsMGTDEPPKXUWvTzcuxyN1wL1QtvVz4e9jzOXM173JSY8e1j+RQ0q1xB8Y1bNNYmtaUiSicqARiI1nL4c9g++eSlpTclmylY=,iv:Gq/ynCqCpil7GDfQpbC42rJPwrI84gdnNq4P9Fblxxw=,tag:ih67h7XDhXrL//Gt7Oms3w==,type:str]
kind: Secret
metadata:
    name: s3-eu-north-1
    namespace: velero
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOG5oTHRvUExFS2hiNTR4
            RGF6NE9wSlhBMWZveC9UZVRpcE5ObkdzclFJCkRvMHprRGp5QktpNHp2NWpXRUR1
            ZEFUdHRpQ2UxS3VPbFhmdHlaTFlEVE0KLS0tIExmL0ZqY2hDMU9PdyswWU0vUGdY
            WVZFQlBNMFFZRWZxNkVMRmFLTm9EekUKXH2KHOWIoGEYuWi+555HOoNUXAusHine
            g62cbrVbYcQd2hng3HT9yErnAa5fzSdniWy15uIBjJ0xG881JENSiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T23:13:59Z"
    mac: ENC[AES256_GCM,data:3xnsUWkcr3PW2WOZVnzsF3ZPd7u5t+vIK6A1OJxqpaQghVYrccSpVYjb/bMQr3CnYGM2nGHgg0lc9GDn1uPwdNlEY0KZOHhRcnqFM/+ogIWERoTCFxJe+k9LtUdgCasaOc2U6ug+g2sjNaHimLp1otDG6fbHsFNZwXAuV7icYrQ=,iv:DxMZvwLZfRGTpfTIj/7VG7oiUyjkY4ODTNkvtkrdZ9o=,tag:U/4qU5LPiZPfQbXinqQ1dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
