apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:nqcP2ubafcAXxy0wC1/ryli3eCEXWveQa5i79UIEOuv/VqJtRQ==,iv:VoQzBDIqqABH8r2h63aXmCSFobV8Dg3iK0qLZ/dtVX4=,tag:B6+I3Ztbm5ku8XFKp0USBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUmIxVXpqYUJyMEZPWWZU
            czFVcFFUT0lHa016a21KUUFnNmx6cGRQbWxNCkxRVTFGZmZKY2VkY1ErR0FkckY0
            YVBjZzZhOVBueFdvTFBBcWUxS3IwV0UKLS0tIFA4WmYzVDNoMHhqcnNXaXdlM0t6
            UHJPanFkVE9ST3U2Vzc1MzJtNmJ0UmMKdK6E7XzIs8wZHAit6tHQAyrr1wlkvhyD
            3iewVSCxX6anIpOb1GZuOnbTUfGaG7umohpNqY5RMAzpOccQ5RMyPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T21:27:07Z"
    mac: ENC[AES256_GCM,data:oBk3avilCVmYmJW77aibSzHEU9mH59jgcMCN+hY+UrJ8BPy4CUJedrYNBR7v3Z7JPEB0EXBLw4SwvW5NJ61rdQlJb9kXrlGaa79TJoQ47OKWjMoB1zaFaMdEpycC+zF/WAQhZGqB2kxGFoIcHtn8FwgqdEmKcFfQx4IEPQYF30I=,iv:ZU7D4ypn22jnWuX1AmNFfhJ4bNELIrX8H9CHnnfIK1M=,tag:445EzjqWnu5CSKEx9FylSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
