apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:dxTOBOpGZjIXL4RNB8GGZjts3RQhVH6/GSSShM6l1OoXrJqb/Q==,iv:DdtwDNxyt3rgVSTUtSBWYmsteZGbOelKrbVxDDuWnW8=,tag:fMJn0neUOnGkzux3iRh4Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTTkyVEIwTVF2ZWJWRDV5
            SEJ5R2NwclJ5THgzQmduSExMUXNNYm10MERzCjllQ1ZicFhqRnRkVmVNTHpnQkh1
            enl6c3BrSHZCWnhkcy81cTEwdmNhY0EKLS0tIFJ2RWoxWVRPcFZTN0xFRzlxYkVu
            aXQ0bWJWYnNGRFlMU09SaEptekJaSlkKKhB+RvhxshgWbSvK67zDuWwBKUK79ZNg
            AQ2UcVs/pXJKmOGIUxOVr2tShxvTFXU2y2b62XIbMnQ4cGPxdu6hpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T23:11:40Z"
    mac: ENC[AES256_GCM,data:heQnxABk5xdmRw1kx3j1kGMt7m6zsN19UZ5TYBWdYmbAfZAfzdBP50dLoAWgEKqtuTGst0YgdU/hDD7QzmAfqXlGbwS02tUWQ2KSdCy1FsV23v/jYOLcr6i0SIaySgTd4Sy6LrNqd3zeph1hfsZJMqx1lxFC6ZvYzsHarsk12pY=,iv:tChbUHgWRB41iT1PqTS3o6Gjk6Vy/IkebRsRvfUSwfs=,tag:diIAVg5MAMlww+zr5aDKwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
