apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:bfPme/fT4nxMlfEUbJwSuYRSij2K60t6DxVbiHScEQXJ0NIM5098nA==,iv:0l6qt/DjuYsPzEvYqf3wldY1SUj4NcQCd40ZMI7CIIk=,tag:/UAt+h30j2/XQUD00P5o+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT0RwVU1NNEJmR3czNzg1
            S1g2OW1ZLzFqMWpSdndqSGRZOUIyVkprNlc0CkI4MWttNCsyRHlVdnNNMVk1c1RJ
            akxsV2MrVkhIeFlVdjNyMjJSVVBRRm8KLS0tIGQ5ZmxaL2RTanM2Y25DVkR4Tmda
            ZWFBYkRDeXJIbDR4ekZzRU83bms3encKPx988UQ37eb+wDez40hDLdxyywFAO0In
            9MMTtSF6w/l0/S5VVy3h4292TaOtqRPPs4OaDnGJDhvQQtkJ5Mnh1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T16:51:44Z"
    mac: ENC[AES256_GCM,data:aEJDud3KWU9BcYx4CJNVs3nGcP3OQ8Tj/G8p3N/yZiTq1x3YH7EU2bnAi1VKhlOPZnkbB5B1Iddjz21myAIM/qIN8DAEhXiyVaQjy9BqY8kwfKwUbYbMBw2aow7Z3ECwZ9bvHtkDekdFwQsa/CTBfobPnA7+qRU/b4Omg6FioUE=,iv:Oug4thco/HrP6sUeT1CvnM/Ckg2cplWcC9J1bGUTdoU=,tag:Q85SKmE++G2BeRzNz5ih1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
