apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:Z2HbYEkyDwIRbvjq5t7Rk+Rp9JLeNLNnIqdhKexHcdAMfky2ww==,iv:Cg9FK47sJmH7iMw8g8fJ4pNJpGrzf+LR0vTS2Mu02ps=,tag:RSn9uxY6PGE5A2yUF7eTgw==,type:str]
    email: ENC[AES256_GCM,data:I8/TH1K1b9I7P2F3nJIh0xv20jLrPA==,iv:IUfCcGol4LoAFWOl3dZNVzpIY3OBTQcPc9wpJvTZT0Q=,tag:lpsMRrSTy56bNPUjzvILwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU2JVZnlqbjd6cWc2OVVE
            YTZycGtobVNCYUlpOHBsRHFOMEVmMThWaTNrCnEwVDBRM1ZrNlEwZXdXQzdVRE1u
            WjBpM1JvRndSMExnOGFJVThJQVliTjgKLS0tIDA5WHpBbG8rWkNPcFpHcnlabjlP
            K083a25pMUlNOEFycmFLQ2tKZFVYSGsK8JxQB03zR3TLxPcqrBacRoek+D0UoyAe
            X0HmkMqXhZYPbQvdszs79jFjAQVnHcq1Vy7MctBOBQwyYdtstCazxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T23:11:40Z"
    mac: ENC[AES256_GCM,data:VreRmqKZUyI+EqVSgaCqIHP64AG9hFTWa42C6/tCY8Hw2b883nsYpsw/cXz2ylnUvM5/vMI1eStzat+bgbUOD01c5Zd7nSaCNKfj6ZJHHjJLjPUyOZS1Ofuk9vhvHSdgBSv4DaV3llcpvOljsE+OsPANS4VHVOo/QrxRCaozBWE=,iv:2VVId+1a+fP5mM8Hn9fsWZNSb2HEQvfjFHyRH1GXYJo=,tag:4213UeuHF3lS0IPehw7Fyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
