apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VQnFMuQ=,iv:r/Kuqgdd1rdea2ZEwq5mhsJTtB8PKOQJdQ7oscjHD7I=,tag:qegvCSsTv7E75BBMTcCveg==,type:str]
    password: ENC[AES256_GCM,data:ZK8HHmS5X00L/uy/hnEHuW2wfdZ2GiKv,iv:BbKkMAcQx7njQOXaHSUbNL451LGIlr5w9O1Xj6xTnrc=,tag:TyFU00jV+MxRzBjGh/cFEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdlRkZzNDdEVnT3ZXaUF1
            ODJQWnE0N3VpOUZ1OGZPVXVjU01aRGNxNGkwCng3ZjlSYzBMRDZCLzhZcmd6dW1R
            M2NvU1BHSW1rcDU5bWxQRnF0UWg3QjgKLS0tIDQrUE9TTG5xMklnMTdFL0ZqKyth
            QS9VTzkvWmRpdUZ3dC9obGN4aXBZU2MK6XnchskkdIoQBl07NB6g6m/UJ79fwfy4
            la+t2sVir/w4rCONToIl+keb0fnacgSHvhDB2IyfPAjzSirlvDu19Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T21:27:07Z"
    mac: ENC[AES256_GCM,data:XRTXcgEVsw+SrYA1leFVUM2RzQfHDf38tzuWMJksvO7cD6BYkXInqEnE9xUMu8olMT0o0UYxLmVWYV4rHeUt0wUC+7Uam7zgPXuAd7IliGKyeYoiJeBqq3Uxq9dZA/jLchzR1XtAZ1qahuwpcH4qtIK2QJQiu+9c/zsSOrR0IiY=,iv:m+zT8V0Gt88PNrNxGiMixjDQwrt5ORQTP/E/BmSjlak=,tag:app3UPRajRV/T10IYmiRUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
