apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nwY8cN9+7kcWAMjaxA==,iv:00MeiA63PC1ihZEZ5rmN7Q2yD1VFT1rItWMXSltH4ao=,tag:Tcrv0UyQDKVjAEKofL6J/w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:WzzycMkryYbSZ3SHhagJXuEGuEI0,iv:DknWHDV2qNiqOSQc55cyF4m9JzdL2PQWMBM2gAGpvU4=,tag:r6+UZpPwP3bOHiakYNLRXw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:3h9m3rhqB8e81fbhMdkia+/Os3zkQA==,iv:RYZ798/VmF24MqmvtbzvqdiUcn9yDh9bH2hOP5tqe/0=,tag:pFsZ0PVwNS9KnGbbr7GwAA==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:63P9gTI5y7chOS8Ns+PPv3cQ3gD+X5qSHuRj8kk4zUgNxQ==,iv:HdYUqeIG9LJzzBwMQGzqc705km6RIQLQ6gDyQX3wg7k=,tag:5UfM05k1WhPQjugHwksGkg==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:ZpDF,iv:4Bn8i8OgD95HZHYX2J60z2QpIxAWDIXsY+zQTUlg8Ko=,tag:EDyDEaq35zpnooBsfETFXQ==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:t0xk0KRrNMcw9iK5nVMV7XmSonm4,iv:KhGINDoeybRF2TiYxnyG+TpD2NlrsfJFWUaTM0a/ras=,tag:OtsyuwWmaXoK27FGOrJiWg==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:LeqRBYHxtDVc9QK3/3kQiISfzq4=,iv:V+8Ub5olcuoU1vrCZS/i6odM2ONuxsFxdhXll+FRfXU=,tag:TXrZq+gOTzXKFNmWAWyYkg==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:XQgiq2ExDyiHyfYCj2q50F/MdMtGQ1BO447Xf6iHS23SMV1L2o727C/RnG8=,iv:0TSJmZqyAuPBkwfngv2rF+MBTHEWVz85uLAQI68MqF8=,tag:/IXKLnceHZrcoOzJn+Ebcg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:s57bPjILvpKmlK+dfn2BZ+qn1w4jlZ9za84Ecfj4xuR6YQPDZSd/rg==,iv:XAtTBmGIdlU3BllLuHETG9Id/GeOBvUlr7pjB3CBoSc=,tag:SP3HgVenNr/XjRy3YSx9rQ==,type:str]
    SECRET_INGRESS_ADDR: ENC[AES256_GCM,data:4m1qm7KmfnRCtJRL834=,iv:8EVtzFjpIbGen6Z4yF9yEFOcsrwmnWBED5okDNzvDyk=,tag:FCwHBfXy94S1VZhy/dPQRA==,type:str]
    SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fPYk652ZJTgKL4x1NakC9yxLv1o=,iv:NuXXNvs87E0hGp/saxesBmHCsbZ89WiW6JXWvcvEPfs=,tag:VN2PwKYC1A7LKGBjXyOI3g==,type:str]
    SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/Hl+YT1LneRySUvEz2GSAgaNUOkywymHk5CgzRcYSDVSbiKnKfwJlQ==,iv:lFxz290Eb6IUHasv4XbczLP5/TxFORGWXXdQhvTZaV4=,tag:eVtTIDUi+xku4ibIGMw7bw==,type:str]
    SECRET_VOLSYNC_REPOSITORY_CTRL: ENC[AES256_GCM,data:z6fQZ/goZqCInoxK97ToiXgYgLT9iqZ7+TsQkiq1kswePMehkJfojBPZTRmb4HQ6O3xM72U3+qc+DS6isTZUVtiJKWfZt4FzfDLdXhE=,iv:WAZ8mGk0uJ/SRYC6OdZtQt0HtJ9wkWOBN3qoJhJVj/M=,tag:y4O5Yy+M06X4jIMaySL7Kw==,type:str]
    SECRET_VOLSYNC_REPOSITORY: ENC[AES256_GCM,data:D1kKGhYTseLfcP2EljC4Lk1TOdfbSJLnV8GFyMyV6x54DoHD7ZLjBmPJz7rQ+ny/PJO4pfq+lUeeX9kZm5dsYUnXtr7Al0jhfkisYq8=,iv:7dOAi4f/gmR5T75aca+Mc6WwJFCtKZnlzmkosc2wCDw=,tag:A/NSDpXT+5xjktG0Lph1xw==,type:str]
    SECRET_VOLSYNC_PASSWORD: ENC[AES256_GCM,data:KtF3ro756DR9,iv:L3lRsUoXZcyWdbdUwOCKPmILu0ooUmGoZyfg2pr33nQ=,tag:b/M5RUY4VSde7GuiUCavvw==,type:str]
    SECRET_VOLSYNC_SCHEDULE: ENC[AES256_GCM,data:RN1snhIpuKQu,iv:XD/p8xR1lV9Azk+6yDjb9KyrX8iJtlglKTtDsJkQpfY=,tag:00+eSBmHwhhHmuXC94ehPg==,type:str]
    SECRET_TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:Y+pk5Xd93rfLjlMhXrjQyfkGvSsafv6EeKqct10HUAJF2RDriTWyuVXgukZAC9tgIzxRqhOG/mQ=,iv:x1amIlD26LSS2DsaR3HUZkEOHPVCKmVDr/oJxJm1x7E=,tag:knFZMRi6ipQqav7WnnAyEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVU1rUXpxZkd2d081OTFQ
            R3hYRTRLT3hTZUhLWEd6UGZnbjlvVzVXRjJNCi91RlRTZE44NUdjNHI2ZHBGc2Fu
            QVJuZFd5MThJWitiRkxTYTBRNnhjSjQKLS0tIEl4ajIvRUsxb214d21jVUVXSzZT
            R1R4akRTN3BxcHNjV0RZS1grNTZZRzAKvPITWW5FFj6OBxATaAqTWpQsT5bwJshF
            womdZAfg9zObnzcju4YSlBlG4pwLHZr62cFIHgWW1eYU3By2p3+AGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T16:51:44Z"
    mac: ENC[AES256_GCM,data:hCFJIFl0sH/TMZ0BNOggrYAy1LIMPDO2AAtANb/5j5rj12Zz0P1/YUtsgvs+4XhcrUfgqBHDvuYxw5euBHOhIRtmME0p5ZpaevkX8KURbK+N4IkSxm5b/I5ohPxztByhzNacbRUht1qnhGzzdv+kPryPfhA1Een7aej7ssIdZ6A=,iv:nayQ1ZGk2+7Im8NTvnhb03FL1XCUlQ056/6puCaBVII=,tag:Oft7lDGydqRjxIiWs3Vppw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
