apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:akxr5C+pT7TfLqhvig==,iv:wLk22xE5Q/bMPRg7EKBKb1GlzP/6MvrWvKQxu40QQgg=,tag:P1Mhfx3te9UZbU0HG7oqtQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1mWZq0GCYgq4P6dgOYzTTyu70xPZ,iv:lg70GMmixvEMgOxePuzNIrEudZJtha+Kf8Q5FMVaat0=,tag:XL+r6dJOX6Suc+pIIRKNkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWmYrTWx1d2RVV2M4YnVN
            UlZFMFIwOXhRWmdRdCtxaFJaeUFTVkZXdkU0CktkSGM5bjE5QjMrVXVic3RHaEZ4
            emU5NjczcXVWRUZzdDhLOWdOYU9DS28KLS0tIHNxa3EwMVlYdlZoZmdSZ1hCTEJE
            elBtMXhMaDJsQkJZcElhMFlYMS9SWUkKGO109ndOPJv/MJ505Hf9d+rIvQ+YUE1n
            elP3KBBrOiUyLrqP4G1+GlxObDkgQ9ADLrPhUKeLwlUQ+Yg0pAczKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T22:34:12Z"
    mac: ENC[AES256_GCM,data:QY3TtXuoN8cbhSZeX4zt/l5kj16ihm+RnMmK84AuWAEQqZEQZ26gyomRjNXFuK467OIwrxaWKf2eXXfe5Qukxv2BOqnf+QRGJmst48pIuerHeBscwpXrDUQHHHQHBMp/dO2Jl87cl9vvHoytaSF01wWS59tKLYVSyeq04m8PlTE=,iv:WwZT815x8+0zoKReYa24C8E3vycZeJo+vOiwGQzFBA8=,tag:7cjAUg3s0XhaSY0jUcj87w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
