apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:T6vbx0TZ53QS8yFpnw==,iv:sM9ydE0kPEE8+YpQ6sDqqBuWkJOZXPs7HV2NYZ+A2YA=,tag:BIdX3BDBcP7Iw0lMw1xCaQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:e7rr8B0R/RoRi6LvJ3XYc3hhs1fO,iv:5NlbJLx4ZqpMniiUB+w5JzL0m9d3/v7tA9+R5y8LmPk=,tag:01a+y2Bh4G9tYjx0dR2mYQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FoVmz3QI/ZyHLfgrYEeHSQvadnoyWQ==,iv:yPhsmc6rfQiPbE8ei5sy24O79nJ+8eZL3pThjKxif+Q=,tag:rbaf/GAjBs3R0EoIxeHt+A==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:I0m1UtuP+WxuTJgm6MaRfh9leIjOp9N2MKgSFie6VaaLYw==,iv:KRZxY20NAdp5sbsWtPqZ7l7wGo48JUeZdr4o4g6vIKs=,tag:oyOHUsx9REJaeT26A9Mrqg==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:KiaV,iv:FQtXtZ0QAJqGctLIhNhh3XYKkp9FevMU1A2YIrgJbRk=,tag:4+xhnHQ2wx0jCplViqz6Nw==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:IABbq4teIF0J8gZaE1wdumkKbHp+,iv:qobJI+dyc4gNb1vNU+qSCEhlG/H7y86AZaMDQqqR2KY=,tag:0nGsciuHKdcchC805STxLg==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:1ZqFdRN8PQXaPwyUPGbMvLHO09E=,iv:/SzjjGBY5bcqSN81EXMrWf+ghLrYrLcynDzhbPoclVE=,tag:DGXLBFvnfiHBIFZjgKkKTw==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:FoyKSUOVjroEyymhEVatVVnIxdIJPmwME1S2fdPprAG7TBVJUr3kGBaRgMU=,iv:7RC4F59sj8jQSaFxhB/0VbL6OHIqaVkMW7Vmtk6IjQ8=,tag:/HyfNNi12cpL02xPqhahLg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:byXtFszUMHFAHnTU1rkD7dYEtqef0AIDMtNS9xqaGOAi0Yw8p6y2wA==,iv:Nw4QjJ7Aa9O7d/eB9FNLrTj9AlKhE9aEvm+ro7WWACU=,tag:6HU5tH1kmuu2an2lv35eww==,type:str]
    SECRET_INGRESS_ADDR: ENC[AES256_GCM,data:daYNv4WIbCvZE2nMApo=,iv:wPKGbgZPke0nmRyf2MuVuLg3dknVXQE2BGK0VExDFa8=,tag:0HjN1+w91Kl0P467r7+l6A==,type:str]
    SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:A0xoK6jWDKtNpkoWi+ryD19lH+Q=,iv:zm4uXjrZh4u+akfvbRkBvtuwwH/OqciLfHaWDAPnAHw=,tag:K5RnPbfVQzJkkl/pHC3Yeg==,type:str]
    SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ljEbu7W4H0nbTLqqZGevSZ+n80sQnyo30j4PJQlGvpsB2NKA3GwM/g==,iv:uqT8GbXzNQdlh0LVsnFjHci+xmbIlGJhZWXZRb1Otn0=,tag:7px57vyY3M7qeu+o7jTBoQ==,type:str]
    SECRET_VOLSYNC_REPOSITORY_CTRL: ENC[AES256_GCM,data:qVJjJImaeVcGE9QuHXiLWsIUY836ttNh95BOEMAlRqhhcZqOaAAd8XhXEHJqsLbFv/7B1ITzE4XzwTygvgp4VwG8lSyBs2MOPWlPtZM=,iv:LxjgCJA59LFDpNSylogoPplug5D0+SUud9TsJ3Zexck=,tag:WWkuzIs38/BhnQQsXSSUtQ==,type:str]
    SECRET_VOLSYNC_REPOSITORY: ENC[AES256_GCM,data:0wF0NLtYtAU2wHpcr2u9n7m26UlVkDaqgeGp5Dxx2taf0BhVSBxX8/1UqnUik61WDIS6iITQyoLN1y06vz0syPP/hBfbU7OjT8sw/Rc=,iv:Acz1tGyp52g1mcWfC4RQqCh88/d4zItYPJCtdckspeM=,tag:CGhRU1sWlwml7yXFqn81yg==,type:str]
    SECRET_VOLSYNC_PASSWORD: ENC[AES256_GCM,data:dFJxQ4ULd52v,iv:v8gW4dEheyfwS7ipmVBm0C47URBlgxKtAZPY14BRVf0=,tag:iAceIACzUuRMr/4Sn5GIbA==,type:str]
    SECRET_VOLSYNC_SCHEDULE: ENC[AES256_GCM,data:fG0xsmm04IXF,iv:LbYU91Hfi/DKsUxAu4VfHhfWNVs9PNfPlmByBwCfP4Q=,tag:YnvP04LjOuUkAkqkUryBiA==,type:str]
    SECRET_TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:wsITNp/gVVItyXSRSxZe9+74vY6zxZbap+N32v862EFVxptAIfXu6fm8BxUCtqsLW3sHAB3mBBU=,iv:YzdSSs1T/NMHSJAqtF4iOGfjhJBlVVlhZkGK4rQIOXI=,tag:yorqKPk14aSBM3+d0dc6ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUmt4VnR3WTMvR21HRmxu
            S29kQVRmMktnRDhmS3VtRmxtYmlpck4wakdVCjFGenhUam83WkM4SGlSSTl4VUQ0
            YkJxM1BaNFk1RVdzQUR5dmdBMkQ0dGcKLS0tIHNHcnBKUlM4TFZJLzViMklGZm9i
            RVZna3JHbUFrdE4welMyRjYxeEhzWkkKFuag8BNlRApPz5+ejvUQxBpOdI7SFR0E
            qOiBsxnlQpnLotu+NUAJhmOvA/iScw5XQFe3BhwZfuTHPSnleG69Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T21:26:33Z"
    mac: ENC[AES256_GCM,data:gFMejadYxe9XHlMW0ete4GH187xSzjK2nUJqzSznn7I3vAAz9rij+PV5Iv4zotwzWtI5IYwZlfKFm2LjMoWDFL3LMUJJeHdVD7jlvMcXLjzkRuLf/0zDEUS+CfXLv+qy2DYAvA7Ddl6JLd75Y6UnOSboUL9t0CfIHuJ/M6/zd/M=,iv:Jl5PNFvZ61fbFdgCH5nv2u/IGeByl+kRnv+YSP3U4bo=,tag:qBurOO0mhqaOxBvuN4DXoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
