apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wHMZ1C32hk7otBSCWw==,iv:YA4Jxo+tCLkdmQsUdAEmOx4Ba0Xo7kD/LP9pU0FMxiI=,tag:FOqxzx7e3nGGP5SMZCKtWg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VqjrWhilnRxrFAZPKYGnTqlDKNQ1,iv:VXe6aqRaftuEcoOonvkm9psEIPt/gAzdm+jLlqHUqaA=,tag:bhma91CSm6zI61+297E9zA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PMq9/UxAh5nC1olguNOs5ZbBKPasUQ==,iv:jxJ5qwY91yB0mFypPumRPE3ryoppwdqpu7QkfY7bdec=,tag:YRFoKNwJmk7MouZS2lejAQ==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:zCJpvNHQlDvKOsR+UAa/WEwxisnKDItD5oJwNGxK9K0jpQ==,iv:NJSEb3uXj+w20GybYl3fZhqhzk+jh+gUa3vIdFHVZ74=,tag:5X1F4qyRSeavCdE2213mCA==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:NUUk,iv:uioTOByjn0307zCdgpyDwJikm458DHvATh5imnhOhaU=,tag:C5g+3dSfwERnGJ/Qj4kizg==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:nshWvm02XJR9iNbVZ6YsvyNqjt76,iv:eznm0MXk8YjzXSHeFLFyI6G0IX1sYdaooXJCzbQc2d8=,tag:5FhNqHcFryMAAGMXUBHieQ==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:bj+8C3OZ1uJc/+Ss9v+91OAtvkU=,iv:OkS+sd8sJWJbdkjvWjI88Ug281z2R3XWIT7sX2VF+Hw=,tag:arXqTJN6ymeXKXLwCLeByw==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:z6miulfllAM4Wa49pp3c9CtKMBvySpzzLvIwkXxxEB4Uo7wCZcT2LzjT/rE=,iv:LcShyPsUTRaF7z4Bc5zJWTsAxYrFf+cwdylmUF9PmSY=,tag:I2pJKoIweUtUGQxjLls6oQ==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:CeY93Ba29lDQxncqLvPBkIVJdpICIVYfSE3Er7KIW8h2FW7Fc8gkrw==,iv:4cLTQ+vaWeYBS/RETX5TP1zWcbcqYZpDeau57mXskSw=,tag:VCIIAy28wOljAJAehHHOCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucVhINndFVzN6LzhkWGN3
            dWZMeVVLSWV0MXVLRHJmRURCaUFjMCtOSmh3Cjg4T3JsR3h5WGk4YWlaOFdMcG9Q
            ZFJWSEJuRzR3VXJXQ3VYODhkUWhlZ3cKLS0tIGk0MWJFYm9QZUdqY1c2NXg4UVNk
            YWc0cVVMNWVwSXpvT2YzWklDdTV3bVEKafqkEZJKBEV5q8GQtTdiK+bV8Og6iSf4
            F9e0OUjL46D+/EBm9Nj8spOcPxvJCxkC6NJC72+THUH1l1bTaxj/JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T23:11:40Z"
    mac: ENC[AES256_GCM,data:HnT+CdhHY/sH5+wz9lHbv160uNSn300ZaOJUkcyQ6xEVaDoEI9w2ZvUsObcX7ljxrSXiIIXvxBKwP38ZLaFsxZbQPtSo2mwdJxAYxlW/cOCYc3//SFrAgkACb3Fb2SXuiFxf++FXoVBXiAdyXbVjIscw7yjU9p02IU2B3uxkSug=,iv:cPwAMXMoB4Q17Q6WGihe1gOJWmSit8exK6Zfuyz7IsA=,tag:cf1spgQzanvFAWRafrhdJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
