apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kKha9KPVn8rVD4oa0g==,iv:1NoFhMnT65qqdhCz2lSOIj+eUcbYseJaYypaH58PV1Q=,tag:z41qgg9tcoQeOT4GHQK8qg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:uVl7Q0xsk3d+Vh4oigH9uR719sDA,iv:yxMCSk9N1mgrQ1euaW9MFeabc+yB7w0WoEIbZVcZayw=,tag:GMEfsLQ6SJrYYCpQpyRjZw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Hqotu9ViNClh/i9kLDRwUbW4EUEarw==,iv:OUXKkZWW87GBbQhxstfYzcPkTeWspMYaB0UZET3z8A8=,tag:suWa9mIDQjy3Hzf/Yn7JEA==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:3OPCmwP6UvfStY39vjdwRgKfblBzD0Me3+T+i/y964hgFQ==,iv:ufxHxfzy1P+uyv74Vbw2ZLYvmBXmeqanH02uTdRg1Bs=,tag:0JXDrszqa4bSNMYSkQXUgg==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:myuX,iv:OMpeBGWmgYaRfkwUI8nVQ0HMy9POG1V17gXaz/T+pbI=,tag:eDAHwY7uVrNBhWzob4BdHg==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:ErFhauEvW1SC4twJlEJnkw/pDOG8,iv:hlOvrin4q5yN/a/Y0mqSil8GCCXBtcWE2Rc5lCybA84=,tag:H94xrNNojqbtOUUNg5HYnw==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:H579wp9Whycvm8RCl+QoLGb6LFY=,iv:ZlrnY/Aaw8WcWTYkHjS1wQpyI5kHxEEpW1xxSTN0pEw=,tag:fIibpOFAdUdxljoIJN0DHQ==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:otvMIKUNFVRSxMUQIcjID3BUHDVAJzIbTGVM7m/QBM5cF4NZzyNxmgLAGjM=,iv:qUw29fzBQ6Al6cFjIMiw/e4tvk4Um1YCW7wfrPcGKg4=,tag:rTdzqSsROAHLs9KtsUVd2Q==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:LU4zYzdeH7WKShwbQwIPYkknLjg9ROYIlfN0lhkQy4qeXkszJFhhrw==,iv:p+N92Tr7UxqcR+MIOpkAV76OuvyegDqhlHbyim2Jt1I=,tag:dMPUTJfdOn1XWyBfD5KrvA==,type:str]
    SECRET_INGRESS_ADDR: ENC[AES256_GCM,data:sda1F8jnXnkz63QUD20=,iv:REbqWmJ0nC/lPuCifKKzZfzg7pSfeZdLgkLKhuvN75s=,tag:L/AmquBDHRQIWP+1KQ15yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Sk1ENmN3MlAzMDZ4NjNn
            Z2xKN2w1NnNIK3pDcjdLM1FlYmNjVEgvalE0CjhZMFc0RDVxZHJxNjlZemMyWUE2
            K1luQ3NPQVJweTBUdDA4VmxSRnBlQWsKLS0tIGtYc0NDWStrSmZQYVR5UGpuamg4
            dFpJOW9zK045Uit4clFDbGNqS1p1cjgKUGArvq2SxB0+k5+eBZAjhb8n1ihazbW8
            EPexBRDQnT+aeYPUXJtt5V6fJ9M4VnRKFMshW7m5TkXX0Iv2N/QO6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T00:20:48Z"
    mac: ENC[AES256_GCM,data:GBL0Z/LqbV99TRerU6f+TTVKCXZCzrP+/udX3gY2pKaWNGW2CU591ZNQU32zBGoIste6P+4LZjiW42WtWIOJ+4rNu+dnXWBT47b09YaIX26cpEypguz5OsnqqaPY7xSfLXI4ORyK8rUXg5N5ExU0S3HS+nQkNgrf6TtWlDV9onQ=,iv:s2l58/a4xD0tXJ0igTLcdUmIhgvyCP3qM9rS+KWr21w=,tag:Lf9y3xB9YPGSbyOxHat6iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
