---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./geth-tailscale/sts.yaml
  #- ./k8s-gateway/ks.yaml
